### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by idkjs** [nicksenger/senger-io#2]
Thanks far sharing this repo, brother. Lots of good stuff in it.

If this is supposed to be an issue then. Will you stop killing it?

Peace to you.

**Comment by idkjs** [comment]
Actually, if you feel like channeling you inner Iyanla Vanzant, maybe you could comment the hell out of this report for us less adept. Maybe start with this file if you dont have the stamina! https://github.com/nicksenger/senger-io/blob/master/src/client/Epics.re.

Thanks again, sir.

**Comment by nicksenger** [comment]
Hey @idkjs , thanks and I'm glad you've found this project helpful!

I can definitely add some comments around that area. The epic reducer hook was my attempt to get something like redux with redux-observable middleware using hooks, so the redux-observable docs could be a good place to get more info on the overall pattern & usage.

Let me know if there are any other places in particular that you're interested in.

**Comment by nicksenger** [comment]
Added some comments to the `useEpicReducer` implementation and also addressed a pretty significant issue there :+1:

**Comment by idkjs** [comment]
You are appreciated! I will be sure to let you know if anything else peaks my interest that I can formulate a thought for. Thank you, sir.

**Comment by idkjs** [comment]
Question. Why are you using reason-react@4.0? https://github.com/nicksenger/senger-io/blob/f31730936c06b3f187bf037149d606c21f833115/package.json#L29

**Comment by idkjs** [comment]
Brother. You are great, writer. Seriously! The way you whipped up that explanation so quickly speaks to your deep understanding of the topic as well as your communication skill. Thanks for sharing some of that. Next time you get that need to share, i guess the logical next file would be https://github.com/nicksenger/senger-io/blob/master/src/client/Epics.re since that is the file implementing `useEpicReducer` is using.

Peace/love to you, sir.

**Comment by nicksenger** [comment]
> Question. Why are you using reason-react@4.0?

I can't remember any particular reason. I'll try to bump it and add some comments to the epics
